create table field
(
    id         int8 generated by default as identity,
    created_at timestamp,
    name       varchar(255) not null,
    selector   varchar(255) not null,
    updated_at timestamp,
    weight     float4       not null,
    primary key (id)
);

create table index
(
    id         int8 generated by default as identity,
    created_at timestamp,
    rank       float4 not null,
    updated_at timestamp,
    lemma_id   int8   not null,
    page_id    int8   not null,
    primary key (id)
);

create table lemma
(
    id         int8 generated by default as identity,
    created_at timestamp,
    frequency  int4         not null,
    lemma      varchar(255) not null,
    updated_at timestamp,
    site_id    int8         not null,
    primary key (id)
);

create table page
(
    id         int8 generated by default as identity,
    code       int4         not null,
    content    TEXT         not null,
    created_at timestamp,
    path       varchar(255) not null,
    updated_at timestamp,
    site_id    int8         not null,
    primary key (id)
);

create table site
(
    id          int8 generated by default as identity,
    created_at  timestamp,
    last_error  varchar(255),
    name        varchar(255) not null unique,
    status      varchar(30),
    status_time timestamp,
    updated_at  timestamp,
    url         varchar(255) not null unique,
    primary key (id)
);

alter table if exists field
    add constraint name_field_fk unique (name);

create index lemmaIndex on lemma (lemma);

create index pathIndex on page (path);

create index urlIndex on site (url);

alter table if exists index
    add constraint lemma_index_fk foreign key (lemma_id) references lemma;

alter table if exists index
    add constraint page_index_fk foreign key (page_id) references page;

alter table if exists lemma
    add constraint site_lemma_fk foreign key (site_id) references site;

alter table if exists page
    add constraint site_page_fk foreign key (site_id) references site;
